#!/usr/bin/env python3
"""Generate Julia's offline wake-reply PCM library and C metadata.

Output is raw signed little-endian PCM: 16 kHz, 16-bit, mono. The script uses
the same DashScope qwen3-tts-flash/Cherry voice as the firmware. Set
DASHSCOPE_API_KEY, or allow the script to read CONFIG_JULIA_AI_API_KEY from the
local sdkconfig. The key is never written to generated files.
"""

from __future__ import annotations

import argparse
import audioop
import io
import json
import os
import random
import re
import struct
import sys
import urllib.request
import wave
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "main/audio/wake_word_config.h"
OUTPUT = ROOT / "main/audio/generated/pcm"
TABLE = ROOT / "main/audio/generated/reply_pcm_table.h"
API_URL = "https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation"
SAMPLE_RATE = 16000
CATALOG_RE = re.compile(
    r'X\(([A-Z0-9_]+),\s*([A-Z_]+),\s*"([^"]+)",\s*"([^"]+\.pcm)",\s*([01])\)'
)


def catalog() -> list[dict[str, object]]:
    source = CONFIG.read_text(encoding="utf-8")
    rows = [
        {"id": m.group(1), "group": m.group(2), "text": m.group(3),
         "filename": m.group(4), "embedded": m.group(5) == "1"}
        for m in CATALOG_RE.finditer(source)
    ]
    if len(rows) < 20:
        raise RuntimeError(f"expected at least 20 catalog entries, found {len(rows)}")
    return rows


def api_key() -> str:
    key = os.environ.get("DASHSCOPE_API_KEY", "").strip()
    if key:
        return key
    sdkconfig = (ROOT / "sdkconfig").read_text(encoding="utf-8")
    match = re.search(r'^CONFIG_JULIA_AI_API_KEY="([^"]+)"', sdkconfig, re.MULTILINE)
    if not match or not match.group(1):
        raise RuntimeError("set DASHSCOPE_API_KEY or configure CONFIG_JULIA_AI_API_KEY")
    return match.group(1)


def request_json(url: str, key: str, payload: dict[str, object]) -> dict[str, object]:
    body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
    request = urllib.request.Request(url, body, {
        "Authorization": "Bearer " + key,
        "Content-Type": "application/json",
    })
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.loads(response.read().decode("utf-8"))


def download(url: str) -> bytes:
    with urllib.request.urlopen(url, timeout=60) as response:
        return response.read()


def decode_wav(data: bytes) -> bytes:
    with wave.open(io.BytesIO(data), "rb") as wav:
        channels, width, rate, frames = (
            wav.getnchannels(), wav.getsampwidth(), wav.getframerate(), wav.getnframes()
        )
        pcm = wav.readframes(frames)
    if width != 2 or channels not in (1, 2):
        raise RuntimeError(f"unsupported WAV: channels={channels} width={width}")
    if channels == 2:
        pcm = audioop.tomono(pcm, 2, 0.5, 0.5)
    if rate != SAMPLE_RATE:
        pcm, _ = audioop.ratecv(pcm, 2, 1, rate, SAMPLE_RATE, None)
    return pcm


def vary_pcm(pcm: bytes, pitch: float, speed: float) -> bytes:
    # A small two-stage resample changes pitch, then compensates duration. The
    # factors stay within +/-3%, keeping artifacts below the speaker noise floor.
    pitched_rate = max(8000, int(SAMPLE_RATE * pitch))
    pitched, _ = audioop.ratecv(pcm, 2, 1, SAMPLE_RATE, pitched_rate, None)
    target_rate = max(8000, int(SAMPLE_RATE * speed / pitch))
    varied, _ = audioop.ratecv(pitched, 2, 1, SAMPLE_RATE, target_rate, None)
    # Add 30 ms silence at each edge to avoid I2S clicks.
    silence = bytes(SAMPLE_RATE * 30 // 1000 * 2)
    return silence + varied + silence


def synthesize(text: str, key: str) -> bytes:
    result = request_json(API_URL, key, {
        "model": "qwen3-tts-flash",
        "input": {"text": text, "voice": "Cherry", "language_type": "Chinese"},
    })
    url = result.get("output", {}).get("audio", {}).get("url")
    if not isinstance(url, str) or not url:
        raise RuntimeError("DashScope response has no audio URL")
    return decode_wav(download(url))


def write_table(rows: list[dict[str, object]]) -> None:
    lines = [
        "#pragma once", "", "/* Generated by tools/gen_reply_pcm.py. */",
        f"#define WAKE_REPLY_PCM_SAMPLE_RATE {SAMPLE_RATE}U", "",
    ]
    for row in rows:
        path = OUTPUT / str(row["filename"])
        size = path.stat().st_size
        if not size or size & 1:
            raise RuntimeError(f"invalid PCM size: {path} ({size})")
        duration = size * 1000 // (SAMPLE_RATE * 2)
        lines += [
            f"#define WAKE_REPLY_{row['id']}_BYTES {size}U",
            f"#define WAKE_REPLY_{row['id']}_DURATION_MS {duration}U",
        ]
    TABLE.parent.mkdir(parents=True, exist_ok=True)
    TABLE.write_text("\n".join(lines) + "\n", encoding="ascii")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--force", action="store_true", help="regenerate existing PCM")
    parser.add_argument("--metadata-only", action="store_true", help="only validate PCM/write header")
    args = parser.parse_args()
    rows = catalog()
    OUTPUT.mkdir(parents=True, exist_ok=True)
    key = "" if args.metadata_only else api_key()
    for position, row in enumerate(rows):
        path = OUTPUT / str(row["filename"])
        if path.exists() and not args.force:
            print(f"keep {path.relative_to(ROOT)}")
            continue
        if args.metadata_only:
            raise RuntimeError(f"missing {path}")
        rng = random.Random(0x4A554C49 + position)
        pitch = 1.0 + rng.uniform(-0.03, 0.03)
        speed = 1.0 + rng.uniform(-0.03, 0.03)
        pcm = vary_pcm(synthesize(str(row["text"]), key), pitch, speed)
        path.write_bytes(pcm)
        print(f"write {path.relative_to(ROOT)} text={row['text']} pitch={pitch:.3f} "
              f"speed={speed:.3f} bytes={len(pcm)}")
    write_table(rows)
    total = sum((OUTPUT / str(row["filename"])).stat().st_size for row in rows)
    embedded = sum((OUTPUT / str(row["filename"])).stat().st_size
                   for row in rows if row["embedded"])
    print(f"generated replies={len(rows)} sd_bytes={total} flash_pcm_bytes={embedded}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(1)
